services:
  fish-speech:
    image: fishaudio/fish-speech:latest-dev
    runtime: nvidia
    ports:
      - "3140:7860"  # For the Fish Speech Gradio web interface
    volumes:
      - ./checkpoints:/opt/fish-speech/checkpoints:ro  # Read-only mount
      - ./outputs:/opt/fish-speech/outputs
      - ./tools:/opt/fish-speech/tools
      - ./fish-speech:/opt/fish-speech/fish-speech
    working_dir: /opt/fish-speech
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - GRADIO_SERVER_NAME=0.0.0.0
    command: >
      sh -c "python tools/check_cuda.py &&
             python tools/run_webui.py"

  fish-agent:
    build:
      context: . 
      dockerfile: Dockerfile.agent
    runtime: nvidia
    ports:
      - "3141:7860"  # For the Fish Agent Gradio web interface (e2e_webui.py)
      - "3144:8080"  # For the API server (api_server.py)
    volumes:
      - ./checkpoints:/opt/fish-speech/checkpoints:ro  # Read-only mount
      - ./outputs:/opt/fish-speech/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - GRADIO_SERVER_NAME=0.0.0.0
